# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080